# Generated by Django 3.0.8 on 2020-08-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_age', models.IntegerField()),
                ('stu_email', models.CharField(max_length=200)),
            ],
        ),
    ]
